# Generated by Django 4.2.19 on 2025-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
